---
# tasks file for oh-my-zsh
- name: Install Zsh
  yum:
    name: zsh
    state: latest
    
- name: Clone the repository
  become: no
  # command: git clone https://github.com/robbyrussell/oh-my-zsh.git /home/user/.oh-my-zsh
  git:
    dest: /home/user/.oh-my-zsh
    repo: https://github.com/robbyrussell/oh-my-zsh.git


- name: Replace .zshrc
  become: no
  copy:
      dest: /home/user/.zshrc # required. Remote absolute path where the file should be copied to. If I(src) is a directory, this must be a directory too. If I(dest) is a nonexistent path and if either I(dest) ends with "/" or I(src) is a directory, I(dest) is created. If I(src) and I(dest) are files, the parent directory of I(dest) isn't created: the task fails if it doesn't already exist.
      remote_src: yes # not required. If C(no), it will search for I(src) at originating/master machine.,If C(yes) it will go to the remote/target machine for the I(src). Default is C(no).,Currently I(remote_src) does not support recursive copying.
      src: /home/user/.oh-my-zsh/templates/zshrc.zsh-template # not required. Local path to a file to copy to the remote server; can be absolute or relative. If path is a directory, it is copied recursively. In this case, if path ends with "/", only inside contents of that directory are copied to destination. Otherwise, if it does not end with "/", the directory itself with all contents is copied. This behavior is similar to Rsync.

- name: Set zsh as default shell
  user: 
    name: user
    shell: /bin/zsh