---
- name: Replace certificate
  hosts: testserver
  become: yes
  gather_facts: no

  vars:
    certificate_path: /tmp/certificate
    url: https://www.3aliens.net
    new_certificate: "{{ lookup('file', 'files/cert.pem') }}"
    
  tasks:
    - name: Replace the certificate on the server
      replace: path={{ certificate_path }} regexp="-----BEGIN CERTIFICATE-----[^<]*-----END CERTIFICATE-----" replace={{ new_certificate }} backup=yes
      register: result

    - name: Reload the httpd service
      service: name=httpd state=reloaded
      when: result is changed

    - name: Collect the contents of the webpage
      uri: url='{{ url }}' return_content='yes'
      register: webpage
      failed_when: "'The site is a test site' not in webpage.content"
      ignore_errors: yes
      when: result is changed

    - name: Restore original certificate if the website does not work
      copy: remote_src=yes src={{result.backup_file }} dest={{ certificate_path }} backup=yes
      when: webpage is failed and result is changed 
    
    - name: Reload httpd after restoring original certificate
      service: name=httpd state=reloaded
      when: webpage is failed and result is changed 
